# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3e5501e0c02b1e424f74eadcfd95e126789402866307be0c041c9fb9faefe1a971169bdb0ceb4fbf8b79f5e561a6b3d563d84ecadf6dc25b32375e8b310f341

test:
  secret_key_base: e1350784189a450d3be320fd4cacb2770278ca5d57805217d8abfae8e4b55f6eb34b65d252b826c14a8bfb69311159d6e18066ea1e232fb9e11f052d82728531

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
